import type { Metadata } from "next";
import { EB_Garamond, League_Spartan, Volkhov } from "next/font/google";
import { Toaster } from "@/Components/ui/sonner"
import "./globals.css";

const garamond = EB_Garamond({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-garamond",
});

const league_spartan = League_Spartan({
  weight: ["300", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-league-spartan",
});

const volkhov = Volkhov({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-volkhov",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${garamond.variable} ${league_spartan.variable} ${volkhov.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
